// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: vision_data.proto

#ifndef PROTOBUF_vision_5fdata_2eproto__INCLUDED
#define PROTOBUF_vision_5fdata_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3005000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3005000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace protobuf_vision_5fdata_2eproto {
// Internal implementation detail -- do not use these members.
struct TableStruct {
  static const ::google::protobuf::internal::ParseTableField entries[];
  static const ::google::protobuf::internal::AuxillaryParseTableField aux[];
  static const ::google::protobuf::internal::ParseTable schema[1];
  static const ::google::protobuf::internal::FieldMetadata field_metadata[];
  static const ::google::protobuf::internal::SerializationTable serialization_table[];
  static const ::google::protobuf::uint32 offsets[];
};
void AddDescriptors();
void InitDefaultsVisionDataImpl();
void InitDefaultsVisionData();
inline void InitDefaults() {
  InitDefaultsVisionData();
}
}  // namespace protobuf_vision_5fdata_2eproto
namespace y2018 {
namespace vision {
class VisionData;
class VisionDataDefaultTypeInternal;
extern VisionDataDefaultTypeInternal _VisionData_default_instance_;
}  // namespace vision
}  // namespace y2018
namespace y2018 {
namespace vision {

// ===================================================================

class VisionData : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:y2018.vision.VisionData) */ {
 public:
  VisionData();
  virtual ~VisionData();

  VisionData(const VisionData& from);

  inline VisionData& operator=(const VisionData& from) {
    CopyFrom(from);
    return *this;
  }
  #if LANG_CXX11
  VisionData(VisionData&& from) noexcept
    : VisionData() {
    *this = ::std::move(from);
  }

  inline VisionData& operator=(VisionData&& from) noexcept {
    if (GetArenaNoVirtual() == from.GetArenaNoVirtual()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }
  #endif
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields();
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields();
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const VisionData& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const VisionData* internal_default_instance() {
    return reinterpret_cast<const VisionData*>(
               &_VisionData_default_instance_);
  }
  static PROTOBUF_CONSTEXPR int const kIndexInFileMessages =
    0;

  void Swap(VisionData* other);
  friend void swap(VisionData& a, VisionData& b) {
    a.Swap(&b);
  }

  // implements Message ----------------------------------------------

  inline VisionData* New() const PROTOBUF_FINAL { return New(NULL); }

  VisionData* New(::google::protobuf::Arena* arena) const PROTOBUF_FINAL;
  void CopyFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void MergeFrom(const ::google::protobuf::Message& from) PROTOBUF_FINAL;
  void CopyFrom(const VisionData& from);
  void MergeFrom(const VisionData& from);
  void Clear() PROTOBUF_FINAL;
  bool IsInitialized() const PROTOBUF_FINAL;

  size_t ByteSizeLong() const PROTOBUF_FINAL;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input) PROTOBUF_FINAL;
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const PROTOBUF_FINAL;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* target) const PROTOBUF_FINAL;
  int GetCachedSize() const PROTOBUF_FINAL { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const PROTOBUF_FINAL;
  void InternalSwap(VisionData* other);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return NULL;
  }
  inline void* MaybeArenaPtr() const {
    return NULL;
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const PROTOBUF_FINAL;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional int64 image_timestamp = 1;
  bool has_image_timestamp() const;
  void clear_image_timestamp();
  static const int kImageTimestampFieldNumber = 1;
  ::google::protobuf::int64 image_timestamp() const;
  void set_image_timestamp(::google::protobuf::int64 value);

  // optional int64 send_timestamp = 2;
  bool has_send_timestamp() const;
  void clear_send_timestamp();
  static const int kSendTimestampFieldNumber = 2;
  ::google::protobuf::int64 send_timestamp() const;
  void set_send_timestamp(::google::protobuf::int64 value);

  // optional double yaw = 3;
  bool has_yaw() const;
  void clear_yaw();
  static const int kYawFieldNumber = 3;
  double yaw() const;
  void set_yaw(double value);

  // @@protoc_insertion_point(class_scope:y2018.vision.VisionData)
 private:
  void set_has_image_timestamp();
  void clear_has_image_timestamp();
  void set_has_send_timestamp();
  void clear_has_send_timestamp();
  void set_has_yaw();
  void clear_has_yaw();

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  ::google::protobuf::internal::HasBits<1> _has_bits_;
  mutable int _cached_size_;
  ::google::protobuf::int64 image_timestamp_;
  ::google::protobuf::int64 send_timestamp_;
  double yaw_;
  friend struct ::protobuf_vision_5fdata_2eproto::TableStruct;
  friend void ::protobuf_vision_5fdata_2eproto::InitDefaultsVisionDataImpl();
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// VisionData

// optional int64 image_timestamp = 1;
inline bool VisionData::has_image_timestamp() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void VisionData::set_has_image_timestamp() {
  _has_bits_[0] |= 0x00000001u;
}
inline void VisionData::clear_has_image_timestamp() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void VisionData::clear_image_timestamp() {
  image_timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_image_timestamp();
}
inline ::google::protobuf::int64 VisionData::image_timestamp() const {
  // @@protoc_insertion_point(field_get:y2018.vision.VisionData.image_timestamp)
  return image_timestamp_;
}
inline void VisionData::set_image_timestamp(::google::protobuf::int64 value) {
  set_has_image_timestamp();
  image_timestamp_ = value;
  // @@protoc_insertion_point(field_set:y2018.vision.VisionData.image_timestamp)
}

// optional int64 send_timestamp = 2;
inline bool VisionData::has_send_timestamp() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void VisionData::set_has_send_timestamp() {
  _has_bits_[0] |= 0x00000002u;
}
inline void VisionData::clear_has_send_timestamp() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void VisionData::clear_send_timestamp() {
  send_timestamp_ = GOOGLE_LONGLONG(0);
  clear_has_send_timestamp();
}
inline ::google::protobuf::int64 VisionData::send_timestamp() const {
  // @@protoc_insertion_point(field_get:y2018.vision.VisionData.send_timestamp)
  return send_timestamp_;
}
inline void VisionData::set_send_timestamp(::google::protobuf::int64 value) {
  set_has_send_timestamp();
  send_timestamp_ = value;
  // @@protoc_insertion_point(field_set:y2018.vision.VisionData.send_timestamp)
}

// optional double yaw = 3;
inline bool VisionData::has_yaw() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void VisionData::set_has_yaw() {
  _has_bits_[0] |= 0x00000004u;
}
inline void VisionData::clear_has_yaw() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void VisionData::clear_yaw() {
  yaw_ = 0;
  clear_has_yaw();
}
inline double VisionData::yaw() const {
  // @@protoc_insertion_point(field_get:y2018.vision.VisionData.yaw)
  return yaw_;
}
inline void VisionData::set_yaw(double value) {
  set_has_yaw();
  yaw_ = value;
  // @@protoc_insertion_point(field_set:y2018.vision.VisionData.yaw)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace vision
}  // namespace y2018

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_vision_5fdata_2eproto__INCLUDED
